FROM node:${NODE_VERSION}-slim

WORKDIR /app
RUN apt-get update && apt-get install -y git curl && rm -rf /var/lib/apt/lists/*
RUN npm install -g nodemon

ENV NODE_ENV=development
ENV PORT=${BACKEND_PORT}
EXPOSE ${BACKEND_PORT}

CMD ["sh", "-c", "npm install && npx nodemon --watch src src/index.js"]
