#!/bin/bash
set -euo pipefail

# ─── Resolve paths ───────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FLEET_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
export FLEET_ROOT

# Source shared library (color helpers, info/warn/error, apply_stack_template)
# shellcheck source=./common.sh
source "${SCRIPT_DIR}/common.sh"

# Guard: no positional arguments accepted
if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  echo "Usage: fleet init"
  echo ""
  echo "  Initialize fleet for the project in the current directory."
  echo "  Reads .fleet/fleet.toml if present; otherwise starts an interactive wizard."
  echo ""
  exit 0
fi

if [ $# -gt 0 ]; then
  error "fleet init takes no arguments. See: fleet init --help"
fi

# ─── Constants ───────────────────────────────────────────────────────────────
# fleet init is a per-project bootstrap: write .fleet/ into the project working
# directory (PWD), not into the CLI install directory (FLEET_ROOT).
FLEET_DIR="${PWD}/.fleet"
FLEET_TOML="${FLEET_DIR}/fleet.toml"

# ─── Helpers ─────────────────────────────────────────────────────────────────

# _PROMPT_RESULT: global used by ask()
_PROMPT_RESULT=""

# ask LABEL DEFAULT — reads a value from /dev/tty, stores in _PROMPT_RESULT.
ask() {
  local label="$1" default="${2:-}"
  if [ -n "$default" ]; then
    printf "  %-38s [%s]: " "${label}" "${default}"
  else
    printf "  %-38s: " "${label}"
  fi
  read -r _PROMPT_RESULT </dev/tty
  _PROMPT_RESULT="${_PROMPT_RESULT:-${default}}"
}

# ask_yn LABEL — reads Y/n; returns 0 for yes, 1 for no.
ask_yn() {
  local label="$1" ans
  printf "  %s [Y/n]: " "${label}"
  if [ -t 0 ]; then
    read -r ans </dev/tty
  else
    ans="y"
    echo "y (no tty — defaulting yes)"
  fi
  case "${ans:-y}" in
    [Nn]*) return 1 ;;
    *)     return 0 ;;
  esac
}

# pick_port DEFAULT — prints a free port, prompting on collision.
pick_port() {
  local default="$1"
  if command -v lsof >/dev/null 2>&1 \
     && lsof -iTCP:"${default}" -sTCP:LISTEN -nP >/dev/null 2>&1; then
    warn "Port ${default} is already in use on the host"
    printf "  Enter alternative port [%s]: " "${default}"
    if [ -t 0 ]; then
      read -r _PROMPT_RESULT </dev/tty
      _PROMPT_RESULT="${_PROMPT_RESULT:-${default}}"
    else
      _PROMPT_RESULT="${default}"
      echo "${default} (no tty — keeping default)"
    fi
  else
    _PROMPT_RESULT="${default}"
  fi
  printf '%s' "${_PROMPT_RESULT}"
}

# generate_feature_base_dockerfile STACKS_ARRAY_NAME OUTPUT_PATH
# Assembles .fleet/fragments into a single Dockerfile at OUTPUT_PATH.
# STACKS_ARRAY_NAME is the name of a bash array variable (passed by name).
generate_feature_base_dockerfile() {
  local -n _stacks="$1"
  local output="$2"
  local fragments_dir="${FLEET_ROOT}/.fleet/fragments"

  # Deduplicate stacks
  local unique_stacks=()
  local seen=""
  for s in "${_stacks[@]}"; do
    case " ${seen} " in *" ${s} "*) continue ;; esac
    unique_stacks+=("${s}")
    seen="${seen} ${s}"
  done

  # Determine which fragments to include (ordered, deduplicated)
  local need_java=false need_node=false need_maven=false need_gradle=false need_postgres=false
  for s in "${unique_stacks[@]}"; do
    case "${s}" in
      spring)  need_java=true; need_node=true; need_maven=true; need_postgres=true ;;
      gradle)  need_java=true; need_node=true; need_gradle=true; need_postgres=true ;;
      node)    need_node=true; need_postgres=true ;;
      next)    need_node=true; need_postgres=true ;;
      vite)    need_node=true; need_postgres=true ;;
    esac
  done

  local stack_label="${unique_stacks[*]}"

  {
    printf "# Generated by fleet init — stacks: %s\n" "${stack_label}"
    printf "# Re-run fleet init to regenerate, or commit this file to version it.\n\n"
    cat "${fragments_dir}/Dockerfile.preamble"
    printf "\n"
    ${need_java}     && { cat "${fragments_dir}/Dockerfile.fragment.java";     printf "\n"; }
    ${need_node}     && { cat "${fragments_dir}/Dockerfile.fragment.node";     printf "\n"; }
    ${need_maven}    && { cat "${fragments_dir}/Dockerfile.fragment.maven";    printf "\n"; }
    ${need_gradle}   && { cat "${fragments_dir}/Dockerfile.fragment.gradle";   printf "\n"; }
    ${need_postgres} && { cat "${fragments_dir}/Dockerfile.fragment.postgres"; printf "\n"; }
    cat "${fragments_dir}/Dockerfile.fragment.dev-user"
    printf "\n"
    cat "${fragments_dir}/Dockerfile.postamble"
  } > "${output}"
}

# ─── Stack inference ─────────────────────────────────────────────────────────

# infer_stack SERVICE_DIR — prints the detected stack type.
# Detection order: next → vite → spring → gradle → go → node → unknown
infer_stack() {
  local dir="$1"
  # 1. Next.js
  if [ -f "${dir}/next.config.js" ] || [ -f "${dir}/next.config.mjs" ] \
  || [ -f "${dir}/next.config.ts" ]; then
    echo "next"; return
  fi
  # 2. Vite
  if [ -f "${dir}/vite.config.js" ] || [ -f "${dir}/vite.config.ts" ] \
  || [ -f "${dir}/vite.config.mjs" ]; then
    echo "vite"; return
  fi
  # 3. Spring (Maven)
  if [ -f "${dir}/pom.xml" ]; then
    echo "spring"; return
  fi
  # 4. Gradle
  if [ -f "${dir}/build.gradle" ] || [ -f "${dir}/build.gradle.kts" ]; then
    echo "gradle"; return
  fi
  # 5. Go
  if [ -f "${dir}/go.mod" ]; then
    echo "go"; return
  fi
  # 6. Node (bare package.json, no framework markers above)
  if [ -f "${dir}/package.json" ]; then
    echo "node"; return
  fi
  echo "unknown"
}

# ─── Hot-reload advisory ─────────────────────────────────────────────────────

# check_hot_reload SVC_DIR STACK — warns about missing hot-reload config.
check_hot_reload() {
  local svc_dir="$1" stack="$2"
  case "${stack}" in
    spring)
      if ! grep -q 'spring-boot-devtools' "${svc_dir}/pom.xml" 2>/dev/null; then
        warn "spring-boot-devtools not found in pom.xml — hot reload disabled"
      fi
      ;;
    go)
      if [ ! -f "${svc_dir}/.air.toml" ]; then
        warn "Air (hot reload for Go) not configured in ${svc_dir}"
        if ask_yn "Generate .air.toml in ${svc_dir##*/}?"; then
          cat > "${svc_dir}/.air.toml" <<'AIRCONF'
root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  stop_on_error = false

[log]
  main_only = false
  time = false
AIRCONF
          info "Generated .air.toml"
        fi
      else
        info "Air config: already present"
      fi
      ;;
  esac
}

# ─── Discover untracked .env files → services[].env_files or [[shared]] ───────
#
# Routing logic:
#   - .env file whose first path component matches a known service dir
#     → written as  env_files = [...]  on that [[services]] block
#   - .env file at the project root level (no matching service dir)
#     → written as  [[shared]]  (mount into every container)

discover_env_files() {
  local proj_root="$1"
  local toml_file="${FLEET_DIR}/fleet.toml"
  local legacy_file="${FLEET_DIR}/shared.env"
  local marker_start="# --- auto-discovered by fleet init ---"
  local marker_end="# --- end auto-discovered ---"

  local -a found=()
  local candidate fname rel_path

  while IFS= read -r candidate; do
    fname="$(basename "${candidate}")"
    case "${fname}" in
      .env.production*|.env.example|.env.sample|.env.template) continue ;;
    esac
    case "${fname}" in
      .env|.env.local|.env.development|.env.development.local|.env.*.local) ;;
      *) continue ;;
    esac
    rel_path="${candidate#${proj_root}/}"
    # Skip git-tracked files
    if git -C "$(dirname "${candidate}")" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
      if git -C "$(dirname "${candidate}")" ls-files --error-unmatch "${candidate}" >/dev/null 2>&1; then
        continue
      fi
    fi
    found+=("${rel_path}")
  done < <(find "${proj_root}" -maxdepth 3 -name '.env*' -type f \
             \( -not -path '*/node_modules/*' -not -path '*/.git/*' \
                -not -path '*/target/*' -not -path '*/dist/*' \) 2>/dev/null)

  [ -f "${toml_file}" ] || error "discover_env_files: ${toml_file} not found (write_fleet_toml should have run first)"

  # ── Classify: service-scoped vs. project-level ──────────────────────────────
  # SVC_DIRS is a global bash array populated by detect_services() / write_fleet_toml().
  local -a project_level_paths=()
  # Parallel arrays replace declare -A for bash 3.2 compatibility (macOS default bash).
  local -a _svc_keys=()   # svc_dir values
  local -a _svc_vals=()   # newline-separated rel-paths for corresponding svc_dir

  local p first_component matched_svc svc rel_to_svc
  for p in "${found[@]+"${found[@]}"}"; do
    first_component="${p%%/*}"
    matched_svc=""
    for svc in "${SVC_DIRS[@]+"${SVC_DIRS[@]}"}"; do
      if [ "${first_component}" = "${svc}" ]; then
        matched_svc="${svc}"
        break
      fi
    done
    if [ -n "${matched_svc}" ]; then
      rel_to_svc="${p#${matched_svc}/}"
      local _found_idx=-1 _ki
      for _ki in "${!_svc_keys[@]}"; do
        if [ "${_svc_keys[${_ki}]}" = "${matched_svc}" ]; then
          _found_idx="${_ki}"
          break
        fi
      done
      if [ "${_found_idx}" -eq -1 ]; then
        _svc_keys+=("${matched_svc}")
        _svc_vals+=("${rel_to_svc}")
      else
        _svc_vals[${_found_idx}]="${_svc_vals[${_found_idx}]}
${rel_to_svc}"
      fi
    else
      project_level_paths+=("${p}")
    fi
  done

  # ── Step 1: patch env_files onto matching [[services]] blocks ────────────────
  # Use Python to rewrite the TOML in-place because bash string manipulation
  # is too fragile for structured file edits.
  if [ "${#_svc_keys[@]}" -gt 0 ]; then
    local pybin
    pybin=$(_find_python_with_tomllib) \
      || error "discover_env_files: python3 with tomllib not found"

    # Build a JSON map:  { "svc_dir": ["rel_path", ...], ... }
    # Pass each svc_dir and its newline-separated paths as separate argv pairs
    # so that newlines inside paths don't confuse word-splitting.
    # We use NUL-delimited pairs fed via a temp file to stay POSIX-safe.
    local svc_env_json
    local _pairs_file; _pairs_file="$(mktemp)"
    local _ki
    for _ki in "${!_svc_keys[@]}"; do
      printf '%s\034%s\035' "${_svc_keys[${_ki}]}" "${_svc_vals[${_ki}]}"
    done > "${_pairs_file}"
    svc_env_json=$(
      "${pybin}" - "${_pairs_file}" <<'PYBUILD'
import sys, json
pairs_file = sys.argv[1]
with open(pairs_file) as fh:
    raw = fh.read()
m = {}
if raw:
    for pair in raw.rstrip('\x1d').split('\x1d'):
        svc_dir, raw_paths = pair.split('\x1c', 1)
        m[svc_dir] = [p for p in raw_paths.split('\n') if p]
print(json.dumps(m))
PYBUILD
    )
    rm -f "${_pairs_file}"

    "${pybin}" - "${toml_file}" "${svc_env_json}" <<'PYEOF'
import sys, re, json

toml_path   = sys.argv[1]
svc_env_map = json.loads(sys.argv[2])   # {svc_dir: [rel_path, ...]}

with open(toml_path) as fh:
    lines = fh.readlines()

out = []
i = 0
while i < len(lines):
    line = lines[i]
    if re.match(r'^\[\[services\]\]', line):
        # Collect entire [[services]] block until next [[ or EOF
        block_lines = [line]
        i += 1
        while i < len(lines) and not re.match(r'^\[\[', lines[i]):
            block_lines.append(lines[i])
            i += 1
        # Identify the service dir
        svc_dir = None
        for bl in block_lines:
            m = re.match(r'^dir\s*=\s*"([^"]+)"', bl)
            if m:
                svc_dir = m.group(1)
                break
        if svc_dir and svc_dir in svc_env_map:
            env_files = svc_env_map[svc_dir]
            env_files_toml = "env_files = [{}]\n".format(
                ", ".join('"{}"'.format(p) for p in env_files)
            )
            # Remove any existing env_files line
            block_lines = [bl for bl in block_lines
                           if not re.match(r'^env_files\s*=', bl)]
            # Insert after run = ... line; fall back to appending before blank tail
            new_block = []
            inserted = False
            for bl in block_lines:
                new_block.append(bl)
                if re.match(r'^run\s*=', bl) and not inserted:
                    new_block.append(env_files_toml)
                    inserted = True
            if not inserted:
                trailing = []
                while new_block and new_block[-1].strip() == '':
                    trailing.insert(0, new_block.pop())
                new_block.append(env_files_toml)
                new_block.extend(trailing)
            out.extend(new_block)
        else:
            out.extend(block_lines)
        continue
    out.append(line)
    i += 1

with open(toml_path, 'w') as fh:
    fh.writelines(out)
PYEOF
  fi

  # ── Step 2: emit project-level paths as [[shared]] blocks between markers ────
  # Idempotency: replace the existing marker block in place on re-run.
  local tmp; tmp="$(mktemp)"
  local inside_block=0 block_written=0
  while IFS= read -r line || [ -n "${line}" ]; do
    if [ "${line}" = "${marker_start}" ]; then
      inside_block=1
      echo "${marker_start}" >> "${tmp}"
      local p
      for p in "${project_level_paths[@]+"${project_level_paths[@]}"}"; do
        printf '[[shared]]\npath = "%s"\n\n' "${p}" >> "${tmp}"
      done
      block_written=1
      continue
    fi
    if [ "${line}" = "${marker_end}" ]; then
      inside_block=0
      echo "${marker_end}" >> "${tmp}"
      continue
    fi
    [ "${inside_block}" -eq 1 ] && continue
    echo "${line}" >> "${tmp}"
  done < "${toml_file}"

  if [ "${block_written}" -eq 0 ]; then
    {
      echo ""
      echo "${marker_start}"
      local p
      for p in "${project_level_paths[@]+"${project_level_paths[@]}"}"; do
        printf '[[shared]]\npath = "%s"\n\n' "${p}"
      done
      echo "${marker_end}"
    } >> "${tmp}"
  fi
  mv "${tmp}" "${toml_file}"

  # Deprecate the legacy file: stop writing it, annotate if it exists so users
  # who still have it around understand the new location.
  if [ -f "${legacy_file}" ]; then
    local dep_line="# DEPRECATED — moved to .fleet/fleet.toml [[shared]] blocks."
    if ! head -n1 "${legacy_file}" | grep -q "^# DEPRECATED"; then
      local ltmp; ltmp="$(mktemp)"
      echo "${dep_line}" > "${ltmp}"
      cat "${legacy_file}" >> "${ltmp}"
      mv "${ltmp}" "${legacy_file}"
    fi
  fi

  local svc_count="${#_svc_keys[@]}"
  local proj_count="${#project_level_paths[@]}"
  info "Discovered ${#found[@]} .env file(s) — ${svc_count} service-scoped (env_files), ${proj_count} project-level ([[shared]])"
}

# ─── Service detection wizard ─────────────────────────────────────────────────

# Populated by detect_services():
SVC_NAMES=()
SVC_DIRS=()
SVC_STACKS=()
SVC_PORTS=()
SVC_BUILDS=()
SVC_RUNS=()

detect_services() {
  local proj_root="$1"
  local svc_dir dname stack

  echo ""
  info "Scanning ${proj_root} for service directories..."
  echo ""

  for svc_dir in "${proj_root}"/*/; do
    [ -d "${svc_dir}" ] || continue
    dname="$(basename "${svc_dir}")"
    case "${dname}" in
      .* | node_modules | target | dist | out | build | .fleet | .git) continue ;;
    esac

    stack=$(infer_stack "${svc_dir}")
    [ "${stack}" = "unknown" ] && continue

    local default_port="3000" default_build="" default_run=""
    case "${stack}" in
      spring)  default_port="8081"; default_build="mvn package -DskipTests -q"; default_run="java -jar /home/developer/${dname}.jar" ;;
      gradle)  default_port="8081"; default_build="gradle build -x test";       default_run="java -jar /home/developer/${dname}.jar" ;;
      go)      default_port="8080"; default_build="go build -o server .";       default_run="/app/${dname}/server" ;;
      node)    default_port="3000"; default_build="npm run build";              default_run="node dist/index.js" ;;
      next)    default_port="3000"; default_build="npm run build";              default_run="npm run dev" ;;
      vite)    default_port="5173"; default_build="npm run build";              default_run="npm run dev" ;;
    esac

    local svc_port="${default_port}"
    local svc_build="${default_build}"
    local svc_run="${default_run}"

    info "Detected service: ${dname} (stack: ${stack}, port: ${svc_port})"

    SVC_NAMES+=("${dname}")
    SVC_DIRS+=("${dname}")
    SVC_STACKS+=("${stack}")
    SVC_PORTS+=("${svc_port}")
    SVC_BUILDS+=("${svc_build}")
    SVC_RUNS+=("${svc_run}")

    info "Added service: ${dname} (${stack})"
  done

  if [ "${#SVC_NAMES[@]}" -eq 0 ]; then
    error "No services detected or selected in ${proj_root}. Ensure service directories contain pom.xml, go.mod, package.json, etc."
  fi
}

# ─── Write canonical fleet.toml ──────────────────────────────────────────────

write_fleet_toml() {
  local proj_root="$1" proj_name="$2" proxy_port="$3" admin_port="$4" db_port="$5" worktree_tmpl="${6:-}"
  local i stack

  mkdir -p "${FLEET_DIR}"

  {
    echo "# fleet.toml — generated by fleet init on $(date '+%Y-%m-%d')"
    echo ""
    echo "[project]"
    echo "name = \"${proj_name}\""
    echo "root = \"${proj_root}\""
    echo "worktree_template = \"${worktree_tmpl}\""
    echo ""
    echo "[ports]"
    echo "proxy = ${proxy_port}"
    echo "admin = ${admin_port}"
    echo "db    = ${db_port}"
    echo ""

    for i in "${!SVC_NAMES[@]}"; do
      echo "[[services]]"
      echo "name  = \"${SVC_NAMES[$i]}\""
      echo "dir   = \"${SVC_DIRS[$i]}\""
      echo "stack = \"${SVC_STACKS[$i]}\""
      echo "port  = ${SVC_PORTS[$i]}"
      echo "build = \"${SVC_BUILDS[$i]}\""
      echo "run   = \"${SVC_RUNS[$i]}\""
      echo ""
    done
  } > "${FLEET_TOML}"

  info "Written: ${FLEET_TOML}"
}

# ─── Write .fleet/.gitignore ─────────────────────────────────────────────────
# Ignores fleet's per-project generated files. Idempotent: won't overwrite
# an existing .gitignore (user may have customized it).
write_fleet_gitignore() {
  local gi="${FLEET_DIR}/.gitignore"
  if [ -f "${gi}" ]; then
    info ".fleet/.gitignore already exists — leaving untouched"
    return
  fi
  cat > "${gi}" <<'GITIGNORE'
# Auto-generated by `fleet init` — fleet's per-project config.
# These are regenerable or machine-specific; do not commit.
fleet.toml
shared.env
host-runner.pid
Dockerfile.feature-base
GITIGNORE
  info "Written: ${gi}"
}

# ─── Prerequisites ───────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || error "docker is not installed"

# ─── Config flow ─────────────────────────────────────────────────────────────
mkdir -p "${FLEET_DIR}"

PROJECT_ROOT=""
PROJECT_NAME=""
PROXY_PORT="3000"
ADMIN_PORT="4000"
DB_PORT="5432"
WORKTREE_TEMPLATE=".worktrees/{name}"

if [ -f "${FLEET_TOML}" ]; then
  info "Found existing ${FLEET_TOML} — reconfiguring idempotently"
  load_fleet_toml

  PROJECT_ROOT="${FLEET_PROJECT_ROOT}"
  PROJECT_NAME="${FLEET_PROJECT_NAME}"
  PROXY_PORT="${FLEET_PORT_PROXY:-3000}"
  ADMIN_PORT="${FLEET_PORT_ADMIN:-4000}"
  DB_PORT="${FLEET_PORT_DB:-5432}"
  # Preserve existing worktree_template if set; otherwise keep the default.
  # NB: can't use ${VAR:-.worktrees/{name}} — bash parameter-expansion braces
  # don't nest, so the first `}` closes the expansion and the second `}` is
  # appended literally, corrupting the template on every re-run.
  if [ -n "${FLEET_WORKTREE_TEMPLATE:-}" ]; then
    WORKTREE_TEMPLATE="${FLEET_WORKTREE_TEMPLATE}"
  else
    WORKTREE_TEMPLATE=".worktrees/{name}"
  fi
  export PROXY_PORT ADMIN_PORT DB_PORT

  # Rebuild SVC_* arrays from loaded TOML using python
  local_pybin=$(_find_python_with_tomllib)
  eval "$(
    "$local_pybin" - "${FLEET_TOML}" <<'PY'
import sys, json
try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib

with open(sys.argv[1], "rb") as fh:
    data = tomllib.load(fh)

services = data.get("services", [])
names  = [s.get("name","")  for s in services]
dirs   = [s.get("dir","")   for s in services]
stacks = [s.get("stack","") for s in services]
ports  = [str(s.get("port","")) for s in services]
builds = [s.get("build","") for s in services]
runs   = [s.get("run","")   for s in services]

def arr(varname, items):
    quoted = " ".join('"{}"'.format(v.replace('"', '\\"')) for v in items)
    print('{}=({})'.format(varname, quoted))

arr("SVC_NAMES",  names)
arr("SVC_DIRS",   dirs)
arr("SVC_STACKS", stacks)
arr("SVC_PORTS",  ports)
arr("SVC_BUILDS", builds)
arr("SVC_RUNS",   runs)
PY
  )"

else
  # Interactive wizard
  if [ ! -t 1 ] && [ ! -t 0 ]; then
    error ".fleet/fleet.toml not found and no terminal available for interactive setup.
  Copy ${FLEET_ROOT}/.fleet/fleet.toml.example to ${FLEET_TOML} and fill it in."
  fi

  echo ""
  echo -e "${GREEN}── Fleet: first-time project setup ──────────────────────────────${RESET}"
  echo ""

  PROJECT_ROOT="$(pwd)"
  info "Project root: ${PROJECT_ROOT}"

  local_default_name=$(basename "${PROJECT_ROOT}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g')
  ask "Project name" "${local_default_name}"; PROJECT_NAME="${_PROMPT_RESULT}"

  PROXY_PORT=$(pick_port "3000"); export PROXY_PORT
  ADMIN_PORT=$(pick_port "4000"); export ADMIN_PORT
  DB_PORT="5432"; export DB_PORT

  ask "Worktree template (use {name} as placeholder)" ".worktrees/{name}"
  WORKTREE_TEMPLATE="${_PROMPT_RESULT}"

  detect_services "${PROJECT_ROOT}"

  write_fleet_toml "${PROJECT_ROOT}" "${PROJECT_NAME}" "${PROXY_PORT}" "${ADMIN_PORT}" "${DB_PORT}" "${WORKTREE_TEMPLATE}"
fi

# ─── Hot-reload advisory (runs without Dockerfile generation now) ─────────────
idx=0
while [ "${idx}" -lt "${#SVC_NAMES[@]}" ]; do
  check_hot_reload "${PROJECT_ROOT}/${SVC_DIRS[$idx]}" "${SVC_STACKS[$idx]}"
  idx=$((idx + 1))
done

# ─── Re-emit canonical fleet.toml (normalize format on idempotent runs) ──────
write_fleet_toml "${PROJECT_ROOT}" "${PROJECT_NAME}" "${PROXY_PORT}" "${ADMIN_PORT}" "${DB_PORT}" "${WORKTREE_TEMPLATE}"

# ─── Seed .fleet/.gitignore (idempotent) ─────────────────────────────────────
write_fleet_gitignore

# ─── Discover .env files → .fleet/shared.env ─────────────────────────────────
discover_env_files "${PROJECT_ROOT}"

# ─── Generate and build project-scoped base image ────────────────────────────
PROJECT_LOCAL_DOCKERFILE="${PWD}/.fleet/Dockerfile.feature-base"

if [ -f "${PROJECT_LOCAL_DOCKERFILE}" ]; then
  ans=""
  printf "  Overwrite existing .fleet/Dockerfile.feature-base? [y/N]: "
  if [ -t 0 ]; then
    read -r ans </dev/tty
  else
    ans="n"
    echo "n (no tty)"
  fi
  case "${ans:-n}" in
    [Yy]*) generate_feature_base_dockerfile SVC_STACKS "${PROJECT_LOCAL_DOCKERFILE}" ;;
    *)     info "Keeping existing .fleet/Dockerfile.feature-base" ;;
  esac
else
  generate_feature_base_dockerfile SVC_STACKS "${PROJECT_LOCAL_DOCKERFILE}"
fi

# Emit the stacks label
UNIQUE_STACKS=()
_seen=""
for _s in "${SVC_STACKS[@]}"; do
  case " ${_seen} " in *" ${_s} "*) continue ;; esac
  UNIQUE_STACKS+=("${_s}")
  _seen="${_seen} ${_s}"
done
info "Generated .fleet/Dockerfile.feature-base from stacks: ${UNIQUE_STACKS[*]}"

FEATURE_BASE_IMAGE="fleet-feature-base-${PROJECT_NAME}"
info "Building project base image ${FEATURE_BASE_IMAGE}..."
docker build --load -t "${FEATURE_BASE_IMAGE}" -f "${PROJECT_LOCAL_DOCKERFILE}" "${FLEET_ROOT}"

# ─── Infra bootstrap ─────────────────────────────────────────────────────────

# Host runner
_runner_pid_file="${FLEET_DIR}/host-runner.pid"
if [[ -f "${_runner_pid_file}" ]] && kill -0 "$(cat "${_runner_pid_file}")" 2>/dev/null; then
  info "Host runner already running (pid $(cat "${_runner_pid_file}")) — skipping"
else
  info "Starting host runner..."
  bash "${FLEET_ROOT}/scripts/fleet-host-runner.sh" &
  echo "$!" > "${_runner_pid_file}" 2>/dev/null || true
fi

# Docker network
if docker network inspect fleet-net >/dev/null 2>&1; then
  info "Network 'fleet-net' already exists — skipping"
else
  info "Creating Docker network 'fleet-net'..."
  docker network create fleet-net
fi

# Gateway: skip entire build+run block if already healthy
if curl -sf "http://localhost:${ADMIN_PORT}/_fleet/api/status" >/dev/null 2>&1; then
  info "Gateway already running and healthy — skipping rebuild"
else
  # Build gateway image
  info "Building gateway image..."
  docker build \
    --load \
    -f "${FLEET_ROOT}/gateway/Dockerfile" \
    -t fleet-gateway \
    "${FLEET_ROOT}"

  # Stop existing gateway container
  if docker inspect fleet-gateway >/dev/null 2>&1; then
    warn "Stopping existing gateway container..."
    docker rm -f fleet-gateway
  fi

  # Start gateway
  info "Starting gateway container..."
  docker run -d \
    --name fleet-gateway \
    --network fleet-net \
    -e PROXY_PORT="${PROXY_PORT}" \
    -e ADMIN_PORT="${ADMIN_PORT}" \
    -e BACKEND_PORT="${BACKEND_PORT:-8080}" \
    -p "${PROXY_PORT}:${PROXY_PORT}" \
    -p "${ADMIN_PORT}:${ADMIN_PORT}" \
    -p "${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}" \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --security-opt label=disable \
    --restart unless-stopped \
    fleet-gateway

  # Wait for gateway
  info "Waiting for gateway to be ready..."
  gw_attempts=0
  until curl -sf "http://localhost:${ADMIN_PORT}/_fleet/api/status" >/dev/null 2>&1; do
    gw_attempts=$((gw_attempts + 1))
    [ "${gw_attempts}" -ge 30 ] && error "Gateway did not start within 30s"
    sleep 1
  done
  info "Gateway is up."
fi

# ─── Install fleet CLI ────────────────────────────────────────────────────────
fleet_bin="${FLEET_ROOT}/fleet"
install_target="/usr/local/bin/fleet"
chmod +x "${fleet_bin}"
if ln -sf "${fleet_bin}" "${install_target}" 2>/dev/null; then
  info "Installed: fleet → ${install_target}"
else
  warn "Could not symlink to /usr/local/bin (permission denied). Run manually:"
  warn "  sudo ln -sf ${fleet_bin} ${install_target}"
fi

# ─── Install /configure-fleet-startup slash command ──────────────────────────
cmd_src="${FLEET_ROOT}/cli/templates/configure-fleet-startup.md"
cmd_dst="${PROJECT_ROOT}/.claude/commands/configure-fleet-startup.md"
if [ -f "${cmd_src}" ]; then
  mkdir -p "$(dirname "${cmd_dst}")"
  cp "${cmd_src}" "${cmd_dst}"
  info "Installed slash command: .claude/commands/configure-fleet-startup.md"
fi

# ─── Install /fleet-debug slash command ──────────────────────────────────────
cmd_src="${FLEET_ROOT}/cli/templates/fleet-debug.md"
cmd_dst="${PROJECT_ROOT}/.claude/commands/fleet-debug.md"
if [ -f "${cmd_src}" ]; then
  mkdir -p "$(dirname "${cmd_dst}")"
  cp "${cmd_src}" "${cmd_dst}"
  info "Installed slash command: .claude/commands/fleet-debug.md"
fi

# ─── Success banner ───────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}┌──────────────────────────────────────────────┐${RESET}"
echo -e "${GREEN}│  Fleet ready                                 │${RESET}"
echo -e "${GREEN}│  Dashboard  → http://localhost:${ADMIN_PORT}          │${RESET}"
echo -e "${GREEN}│  Proxy      → http://localhost:${PROXY_PORT}          │${RESET}"
echo -e "${GREEN}│  Backend    → http://localhost:${BACKEND_PORT:-8080}          │${RESET}"
echo -e "${GREEN}└──────────────────────────────────────────────┘${RESET}"
echo ""
echo -e "${GREEN}Tip:${RESET} open ${PROJECT_ROOT} in Claude Code and run ${GREEN}/configure-fleet-startup${RESET}"
echo "     to verify service health and tune build/run commands."
