#!/bin/bash
# config/node-reconcile.sh — crash-safe node_modules reconcile for fleet feature stacks.
#
# Baked into the feature-base image (COPY -> /usr/local/bin/fleet-node-reconcile.sh) and
# invoked from the per-service start wrapper generated by entrypoint.sh, with CWD set to the
# service dir (so package.json / node_modules are in `.`). $1 is the service name (for logs
# and a per-service npm cache dir). This is a SEPARATE file — not inlined into the
# `python3 -c "..."` generator in entrypoint.sh — precisely so its `"`, `$`, `\;` and globs
# are not subject to that generator's shell/Python double-escaping (a past source of a
# broken entrypoint). Keep it here; have the wrapper CALL it.
#
# WHY THIS EXISTS
# node_modules is a named-volume MOUNTPOINT, so it can never be renamed away as a whole. A
# bare in-place `npm install` on every start mutates the LIVE tree with atomic renames
# (`pkg` -> `.pkg-XXXXXX` -> `pkg`). If that is interrupted (container SIGKILL during
# `fleet sync --rebuild`) or trips on a stale temp entry, it leaves a half-written package
# (e.g. vite/dist present but vite/bin/vite.js missing -> .bin/vite dangling), and the very
# next `exec vite` / `npm run dev` dies -> supervisord FATAL -> gateway 502. This script
# makes the reconcile crash-safe and self-healing.
#
# STRATEGY
#   fast path   — a deps-hash marker + a health check let an unchanged, healthy tree skip
#                 the whole reconcile (node_modules is hundreds of MB; a per-boot copy would
#                 be a real regression).
#   staged path — otherwise install into a STAGING dir on the SAME volume (npm's renames
#                 stay intra-filesystem and atomic), verify it resolves, then swap it into
#                 the live mountpoint with intra-volume renames (no full-tree copy). The live
#                 tree is only ever touched with a verified-good result.
#   self-heal   — if the live tree is itself broken (the corrupt-half case) and staging
#                 failed, clean-install in place so the container recovers unattended rather
#                 than crash-looping on a missing binary.
set -u
NAME="${1:-app}"

[ -f package.json ] || exit 0

# Keep npm's cache off the volume/bind (avoids root-owned-cache EACCES and cross-fs churn).
export npm_config_cache="${npm_config_cache:-/tmp/.npm-cache-${NAME}}"

# A node_modules tree is "good" iff BOTH: (a) npm resolves the top level (`npm ls` exits 0)
# — catches missing/wrong-version deps; AND (b) no `.bin` entry is a dangling symlink —
# catches the half-written-package corruption that `npm ls` alone MISSES and that makes
# `exec vite` die. $1 = the dir CONTAINING node_modules (the app dir or the stage dir).
nm_ok() {
  ( cd "$1" && npm ls --all=false --depth=0 --silent >/dev/null 2>&1 ) || return 1
  [ -d "$1/node_modules/.bin" ] || return 0
  # `-type l ! -exec test -e {} \;` selects dangling symlinks; any hit => corruption.
  ! find "$1/node_modules/.bin" -maxdepth 1 -type l ! -exec test -e {} \; -print 2>/dev/null | grep -q .
}

# Purge stale npm atomic-rename temp dirs (`.pkg-XXXXXX`) — what a prior interrupted install
# leaves behind, and what makes the next rename fail with ENOTDIR/ENOTEMPTY.
purge_tmp() { [ -d "$1" ] && find "$1" -maxdepth 2 -type d -name ".*-????????" -exec rm -rf {} + 2>/dev/null || true; }

# Deps fingerprint: hash the lockfile (or package.json when no lockfile). A matching marker
# on a healthy tree means "nothing to do".
DEPS_SRC=package-lock.json
[ -f "$DEPS_SRC" ] || DEPS_SRC=npm-shrinkwrap.json
[ -f "$DEPS_SRC" ] || DEPS_SRC=package.json
WANT_HASH="$( (sha1sum "$DEPS_SRC" 2>/dev/null || shasum "$DEPS_SRC" 2>/dev/null || md5sum "$DEPS_SRC" 2>/dev/null) | awk '{print $1}')"
HAVE_HASH="$(cat node_modules/.fleet-deps-hash 2>/dev/null || true)"

purge_tmp node_modules

if [ -n "$WANT_HASH" ] && [ "$WANT_HASH" = "$HAVE_HASH" ] && nm_ok .; then
  echo "[fleet] ${NAME} node_modules up to date (deps unchanged, tree resolves) - skipping reconcile."
  exit 0
fi

echo "[fleet] Reconciling ${NAME} node_modules (arch=$(uname -m))..."

STAGE="node_modules/.fleet-stage"
rm -rf "$STAGE" 2>/dev/null || true
mkdir -p "$STAGE/node_modules"
cp -f package.json "$STAGE"/ 2>/dev/null || true
[ -f package-lock.json ] && cp -f package-lock.json "$STAGE"/ 2>/dev/null || true
[ -f npm-shrinkwrap.json ] && cp -f npm-shrinkwrap.json "$STAGE"/ 2>/dev/null || true
[ -f .npmrc ] && cp -f .npmrc "$STAGE"/ 2>/dev/null || true

# Seed staging from the current live tree (hardlinks -> near-free, same volume) so npm only
# does incremental work. Fall back to a plain copy if hardlinking is unavailable.
if [ -d node_modules ] && [ "$(ls -A node_modules 2>/dev/null | grep -vFx '.fleet-stage' | head -c1)" != "" ]; then
  ( cd node_modules \
      && find . -mindepth 1 -maxdepth 1 ! -name '.fleet-stage' -exec cp -al {} "../$STAGE/node_modules/" \; 2>/dev/null \
      || find . -mindepth 1 -maxdepth 1 ! -name '.fleet-stage' -exec cp -a  {} "../$STAGE/node_modules/" \; ) 2>/dev/null || true
  purge_tmp "$STAGE/node_modules"
fi

( cd "$STAGE" && npm install --no-audit --no-fund --loglevel=error ) 2>/dev/null || true

if nm_ok "$STAGE"; then
  # Staged tree resolves — swap it into place. Move the OLD live contents aside, then move
  # the staged children in; all intra-volume renames (atomic, no full-tree copy). Never
  # rename the mountpoint itself — only replace its contents.
  OLD="node_modules/.fleet-old-$$"
  mkdir -p "$OLD"
  ( cd node_modules && for e in *; do
      [ "$e" = ".fleet-stage" ] && continue
      [ "$e" = "$(basename "$OLD")" ] && continue
      mv "$e" "../$OLD/" 2>/dev/null || true
    done )
  ( cd "$STAGE/node_modules" && for e in * .[!.]*; do
      [ -e "$e" ] || continue
      mv "$e" "../../" 2>/dev/null || true
    done )
  printf '%s' "$WANT_HASH" > node_modules/.fleet-deps-hash 2>/dev/null || true
  rm -rf "$OLD" 2>/dev/null || true
  echo "[fleet] node_modules reconcile OK (staged)."
elif nm_ok .; then
  echo "[fleet] WARN: staged reconcile failed; live node_modules still resolves - continuing on it."
else
  # Both broken (corrupt-half case). Self-heal with a clean in-place install.
  echo "[fleet] WARN: node_modules corrupt and staged reconcile failed - clean-installing in place."
  find node_modules -mindepth 1 -maxdepth 1 ! -name '.fleet-stage' -exec rm -rf {} + 2>/dev/null || true
  if npm install --no-audit --no-fund --loglevel=error; then
    printf '%s' "$WANT_HASH" > node_modules/.fleet-deps-hash 2>/dev/null || true
  else
    echo "[fleet] ERROR: clean node_modules install failed; frontend may not start."
  fi
fi
rm -rf "$STAGE" 2>/dev/null || true
exit 0
