#!/bin/bash
# verify-sync-rebuild.sh — HITL verification: sync-rebuild for a plan-built Vite feature.
#
# Lifecycle:
#   1. Create a minimal Vite project in a temp directory.
#   2. Write a plan-built fleet.toml (Vite stack auto-detected from vite.config.js).
#   3. Run fleet init (generates Dockerfile.feature-base, boots gateway).
#   4. Run fleet add --direct (starts the feature container).
#   5. Print the dashboard URL and the source file path for the operator.
#   6. Walk the operator through editing the file and clicking sync-rebuild.
#   7. Wait for operator pass/fail input.
#   8. Tear down the fleet feature on EXIT (trap).
#
# Exit codes:
#   0  — operator entered "pass"
#   1  — operator entered "fail", or setup/prerequisite error
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FLEET_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
FLEET_BIN="${FLEET_ROOT}/fleet"

# ─── Color helpers ────────────────────────────────────────────────────────────
if [ -t 1 ]; then
  GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BLUE='\033[0;34m'; RESET='\033[0m'
else
  GREEN='' YELLOW='' RED='' BLUE='' RESET=''
fi
info()  { echo -e "${GREEN}[verify-sync]${RESET} $*"; }
warn()  { echo -e "${YELLOW}[verify-sync]${RESET} $*"; }
err()   { echo -e "${RED}[verify-sync] ERROR:${RESET} $*" >&2; }

# ─── State (used in cleanup) ──────────────────────────────────────────────────
VERIFY_TMP=""
FEATURE_NAME="vite-smoke-$$"
FEATURE_ADDED=false
GATEWAY_STARTED=false
DASHBOARD_PORT=4000

# ─── EXIT trap: tear down fleet feature and temp dir ─────────────────────────
cleanup() {
  local rc=$?
  set +e   # prevent cleanup errors from masking the real exit code
  if [ "${FEATURE_ADDED}" = "true" ] && [ -d "${VERIFY_TMP}/project" ]; then
    info "Removing fleet feature '${FEATURE_NAME}'..."
    (cd "${VERIFY_TMP}/project" && "${FLEET_BIN}" rm "${FEATURE_NAME}" 2>/dev/null) || true
  fi
  if [ "${GATEWAY_STARTED}" = "true" ]; then
    info "Stopping gateway (started by this script)..."
    docker stop fleet-gateway 2>/dev/null || true
    docker rm -f fleet-gateway 2>/dev/null || true
  fi
  # Remove the project-local base image built for this verify run
  docker rmi "fleet-feature-base-verify-sync" 2>/dev/null || true
  if [ -n "${VERIFY_TMP}" ] && [ -d "${VERIFY_TMP}" ]; then
    info "Removing temp project ${VERIFY_TMP}..."
    rm -rf "${VERIFY_TMP}"
  fi
  exit "${rc}"
}
trap cleanup EXIT

# ─── Prerequisites ────────────────────────────────────────────────────────────
for _req in docker git; do
  command -v "${_req}" >/dev/null 2>&1 || { err "${_req} not found on PATH"; exit 1; }
done
[ -x "${FLEET_BIN}" ] || { err "fleet binary not found at ${FLEET_BIN}"; exit 1; }

# ─── Step 1: create a minimal plan-built Vite project ────────────────────────
VERIFY_TMP="$(mktemp -d "${TMPDIR:-/tmp}/fleet-verify-sync-XXXXXX")"
PROJECT_DIR="${VERIFY_TMP}/project"
mkdir -p "${PROJECT_DIR}/frontend/src"

info "Creating plan-built Vite project at ${PROJECT_DIR}..."

# vite.config.js — its presence triggers the Vite stack in fleet init's planner
cat > "${PROJECT_DIR}/frontend/vite.config.js" <<'VITE'
import { defineConfig } from 'vite'
export default defineConfig({
  server: { port: 5173, host: '0.0.0.0' }
})
VITE

cat > "${PROJECT_DIR}/frontend/package.json" <<'PKG'
{
  "name": "verify-frontend",
  "version": "0.1.0",
  "scripts": {
    "dev":   "vite",
    "build": "vite build"
  },
  "dependencies": {
    "vite": "^6.0.0"
  }
}
PKG

# index.html — vite build requires an HTML entry point in the project root
cat > "${PROJECT_DIR}/frontend/index.html" <<'HTML'
<!DOCTYPE html>
<html lang="en">
  <head><meta charset="UTF-8" /><title>Verify App</title></head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
HTML

# Minimal JS entry point imported by index.html
cat > "${PROJECT_DIR}/frontend/src/main.js" <<'JS'
document.getElementById('root').textContent = 'Hello fleet — edit App.jsx to verify sync-rebuild'
JS

# Source file the operator will edit to exercise sync-rebuild
SOURCE_FILE="${PROJECT_DIR}/frontend/src/App.jsx"
cat > "${SOURCE_FILE}" <<'JSX'
export default function App() {
  return <h1>Hello fleet — edit this file to verify sync-rebuild</h1>
}
JSX

# fleet requires a git repository at [project].root
git -C "${PROJECT_DIR}" init -q
git -C "${PROJECT_DIR}" add -A
git -C "${PROJECT_DIR}" \
  -c user.email="verify@fleet.local" \
  -c user.name="Fleet Verify" \
  commit -qm "init: plan-built Vite project for sync-rebuild verification"

# Write fleet.toml — the auto-generated shape produced by fleet init when it
# detects a vite.config.js (the "plan-built" part of this test scenario).
mkdir -p "${PROJECT_DIR}/.fleet"
cat > "${PROJECT_DIR}/.fleet/fleet.toml" <<TOML
# fleet.toml — generated by fleet init (plan-built Vite stack detection)
# Re-run fleet init to regenerate, or commit this file to version it.
[project]
name = "verify-sync"
root = "${PROJECT_DIR}"
path = "${PROJECT_DIR}/.worktrees/{name}"

[ports]
proxy = 3000
admin = ${DASHBOARD_PORT}
db    = 0

[[services]]
name  = "frontend"
dir   = "frontend"
stack = "vite"
port  = 5173
build = "npm run build"
run   = "npm run dev"
TOML

# ─── Step 2: fleet init — generate Dockerfile.feature-base and boot gateway ──
# fleet init reads the existing fleet.toml non-interactively when it already
# exists, assembles .fleet/Dockerfile.feature-base from the Vite fragments,
# builds the project-local base image, and starts the gateway if not healthy.
if curl -sf "http://localhost:${DASHBOARD_PORT}/_fleet/api/status" >/dev/null 2>&1; then
  info "Gateway already running on port ${DASHBOARD_PORT}."
else
  GATEWAY_STARTED=true   # set before fleet init so cleanup fires correctly
fi

info "Running fleet init (generates Dockerfile.feature-base, boots gateway if needed)..."
(cd "${PROJECT_DIR}" && "${FLEET_BIN}" init)

# ─── Step 3: fleet add --direct — start the feature container ────────────────
# --direct bind-mounts PROJECT_DIR (no git worktree required).
info "Adding feature '${FEATURE_NAME}' in direct mode..."
(cd "${PROJECT_DIR}" && "${FLEET_BIN}" add "${FEATURE_NAME}" \
  --title "Verify Sync-Rebuild (plan-built Vite)" \
  --direct)
FEATURE_ADDED=true

# ─── Step 4: print dashboard URL and source file path ────────────────────────
DASHBOARD_URL="http://localhost:${DASHBOARD_PORT}"
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════════╗${RESET}"
echo -e "${GREEN}║  HITL verify: dashboard sync-rebuild (plan-built Vite feature)   ║${RESET}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════════╝${RESET}"
echo ""
echo -e "  Dashboard URL : ${BLUE}${DASHBOARD_URL}${RESET}"
echo -e "  File to edit  : ${BLUE}${SOURCE_FILE}${RESET}"
echo ""
echo -e "${YELLOW}Steps:${RESET}"
echo "  1. Open the dashboard at ${DASHBOARD_URL}"
echo "  2. Locate the feature card for '${FEATURE_NAME}'"
echo "  3. Edit the file shown above — change the <h1> text to something new"
echo "  4. In the dashboard card, click 'Sync' or 'Rebuild' (the sync-rebuild button)"
echo "  5. Wait for the rebuild to complete, then reload the proxied URL to confirm"
echo "     the updated content is served"
echo ""

# ─── Step 5: wait for operator pass/fail ─────────────────────────────────────
_RESULT=""
printf "  Result [pass/fail]: "
read -r _RESULT </dev/tty || _RESULT="fail"

case "${_RESULT}" in
  pass|PASS|p|P)
    info "Operator result: PASS ✓"
    exit 0
    ;;
  fail|FAIL|f|F)
    err "Operator result: FAIL ✗"
    exit 1
    ;;
  *)
    warn "Unrecognised input '${_RESULT}' — treating as FAIL"
    exit 1
    ;;
esac
