import { useState, useCallback, useEffect } from 'react';

const STORAGE_KEY = 'fleet.reviewNotes.v1';

/**
 * Per-worktree review notes, persisted to localStorage under 'fleet.reviewNotes.v1'.
 *
 * Each note has the shape:
 *   { id, refKind, selectors, label, route, text, createdAt }
 *
 * id and createdAt are generated by addNote; the rest come from the caller.
 *
 * @returns {{ notesByWorktree: Object.<string, Array>, addNote: Function, removeNote: Function, clearForWorktree: Function }}
 */
export function useReviewNotes() {
  const [notesByWorktree, setNotesByWorktree] = useState(() => {
    try {
      if (typeof localStorage === 'undefined') return {};
      return JSON.parse(localStorage.getItem(STORAGE_KEY)) ?? {};
    } catch {
      return {};
    }
  });

  useEffect(() => {
    try {
      if (typeof localStorage !== 'undefined') {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(notesByWorktree));
      }
    } catch {
      /* ignore persistence errors (e.g. storage full / SSR) */
    }
  }, [notesByWorktree]);

  const addNote = useCallback((worktree, note) => {
    const newNote = {
      ...note,
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
    };
    setNotesByWorktree(prev => ({
      ...prev,
      [worktree]: [...(prev[worktree] ?? []), newNote],
    }));
  }, []);

  const removeNote = useCallback((worktree, id) => {
    setNotesByWorktree(prev => ({
      ...prev,
      [worktree]: (prev[worktree] ?? []).filter(n => n.id !== id),
    }));
  }, []);

  const clearForWorktree = useCallback((worktree) => {
    setNotesByWorktree(prev => {
      const next = { ...prev };
      delete next[worktree];
      return next;
    });
  }, []);

  return { notesByWorktree, addNote, removeNote, clearForWorktree };
}
