import { useState, useCallback } from 'react';

/**
 * In-memory store of review notes, keyed by worktree name.
 *
 * Each note has the shape:
 *   { id, refKind, selector, label, route, text, createdAt }
 *
 * id and createdAt are generated by addNote; the rest come from the caller.
 *
 * @returns {{ notesByWorktree: Object.<string, Array>, addNote: Function, removeNote: Function, clearForWorktree: Function }}
 */
export function useReviewNotes() {
  const [notesByWorktree, setNotesByWorktree] = useState({});

  const addNote = useCallback((worktree, note) => {
    const newNote = {
      ...note,
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
    };
    setNotesByWorktree(prev => ({
      ...prev,
      [worktree]: [...(prev[worktree] ?? []), newNote],
    }));
  }, []);

  const removeNote = useCallback((worktree, id) => {
    setNotesByWorktree(prev => ({
      ...prev,
      [worktree]: (prev[worktree] ?? []).filter(n => n.id !== id),
    }));
  }, []);

  const clearForWorktree = useCallback((worktree) => {
    setNotesByWorktree(prev => {
      const next = { ...prev };
      delete next[worktree];
      return next;
    });
  }, []);

  return { notesByWorktree, addNote, removeNote, clearForWorktree };
}
